const locationList = [
  {
    distrito: "Aveiro",
    concelho: [
      "Águeda",
      "Albergaria-a-Velha",
      "Anadia",
      "Arouca",
      "Aveiro",
      "Castelo de Paiva",
      "Espinho",
      "Estarreja",
      "Ílhavo",
      "Mealhada",
      "Murtosa",
      "Oliveira de Azeméis",
      "Oliveira do Bairro",
      "Ovar",
      "Santa Maria da Feira",
      "São João da Madeira",
      "Sever do Vouga",
      "Vagos",
      "Vale de Cambra",
    ],
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Ilha_Dos_Puxadoiros_%2847261194681%29_%28cropped%29.jpg/1920px-Ilha_Dos_Puxadoiros_%2847261194681%29_%28cropped%29.jpg",
  },
  {
    distrito: "Beja",
    concelho: [
      "Aljustrel",
      "Almodôvar",
      "Alvito",
      "Barrancos",
      "Beja",
      "Castro Verde",
      "Cuba",
      "Ferreira do Alentejo",
      "Mértola",
      "Moura",
      "Odemira",
      "Ourique",
      "Serpa",
      "Vidigueira",
    ],
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Castelo_de_Beja_2_%28cropped%29.JPG/1920px-Castelo_de_Beja_2_%28cropped%29.JPG",
  },
  {
    distrito: "Braga",
    concelho: [
      "Amares",
      "Barcelos",
      "Braga",
      "Cabeceiras de Basto",
      "Celorico de Basto",
      "Esposende",
      "Fafe",
      "Guimarães",
      "Póvoa de Lanhoso",
      "Terras de Bouro",
      "Vieira do Minho",
      "Vila Nova de Famalicão",
      "Vila Verde",
      "Vizela",
    ],
    image:
      "    https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Braga_Banco_Portugal_%28cropped%29.jpg/800px-Braga_Banco_Portugal_%28cropped%29.jpg",
  },
  {
    distrito: "Bragança",
    concelho: [
      "Alfândega da Fé",
      "Bragança",
      "Carrazeda de Ansiães",
      "Freixo de Espada à Cinta",
      "Macedo de Cavaleiros",
      "Miranda do Douro",
      "Mirandela",
      "Mogadouro",
      "Torre de Moncorvo",
      "Vila Flor",
      "Vimioso",
      "Vinhais",
    ],
    image:
      "https://upload.wikimedia.org/wikipedia/commons/1/1c/Cruzeiro_do_Outeiro_4.jpg",
  },
  {
    distrito: "Castelo Branco",
    concelho: [
      "Belmonte",
      "Castelo Branco",
      "Covilhã",
      "Fundão",
      "Idanha-a-Nova",
      "Oleiros",
      "Penamacor",
      "Proença-a-Nova",
      "Sertã",
      "Vila de Rei",
      "Vila Velha de Ródão",
    ],
    image:
      "https://upload.wikimedia.org/wikipedia/commons/f/fb/Jos%C3%A9_Castelo_Branco_MalucoBeleza_%28cropped%29.png ",
  },
  {
    distrito: "Coimbra",
    concelho: [
      "Arganil",
      "Cantanhede",
      "Coimbra",
      "Condeixa-a-Nova",
      "Figueira da Foz",
      "Gois",
      "Lousã",
      "Mira",
      "Miranda do Corvo",
      "Montemor-o-Velho",
      "Oliveira do Hospital",
      "Pampilhosa da Serra",
      "Penacova",
      "Penela",
      "Soure",
      "Tábua",
      "Vila Nova de Poiares",
    ],
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/cd/Coimbra_e_o_rio_Mondego_%286167200429%29_%28cropped%29.jpg",
  },
  {
    distrito: "Évora",
    concelho: [
      "Alandroal",
      "Arraiolos",
      "Borba",
      "Estremoz",
      "Évora",
      "Montemor-o-Novo",
      "Mora",
      "Mourão",
      "Portel",
      "Redondo",
      "Reguengos de Monsaraz",
      "Vendas Novas",
      "Viana do Alentejo",
      "Vila Viçosa",
    ],
    image: "https://www.portugal-live.net/images/rotator/351-evora-a.jpg",
  },
  {
    distrito: "Faro",
    concelho: [
      "Albufeira",
      "Alcoutim",
      "Aljezur",
      "Castro Marim",
      "Faro",
      "Lagoa",
      "Lagos",
      "Loulé",
      "Monchique",
      "Olhão",
      "Portimão",
      "São Brás de Alportel",
      "Silves",
      "Tavira",
      "Vila do Bispo",
      "Vila Real de Santo António",
    ],
    image:
      "https://www.flyedelweiss.com/SiteCollectionImages/Destinations/Faro/faro-sea.jpg",
  },
  {
    distrito: "Guarda",
    concelho: [
      "Aguiar da Beira",
      "Almeida",
      "Celorico da Beira",
      "Figueira de Castelo Rodrigo",
      "Fornos de Algodres",
      "Gouveia",
      "Guarda",
      "Manteigas",
      "Mêda",
      "Pinhel",
      "Sabugal",
      "Seia",
      "Trancoso",
      "Vila Nova de Foz Côa",
    ],
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Guarda_Catedral_2_%28cropped%29.jpg/800px-Guarda_Catedral_2_%28cropped%29.jpg",
  },
  {
    distrito: "Leiria",
    concelho: [
      "Alcobaça",
      "Alvaiázere",
      "Ansião",
      "Batalha",
      "Bombarral",
      "Caldas da Rainha",
      "Castanheira de Pêra",
      "Figueiró dos Vinhos",
      "Leiria",
      "Marinha Grande",
      "Nazaré",
      "Óbidos",
      "Pedrógão Grande",
      "Peniche",
      "Pombal",
      "Porto de Mós",
    ],
    image:
      "https://www.portugaldenorteasul.pt/uploads/20190713224905_asaaass.jpg",
  },
  {
    distrito: "Lisboa",
    concelho: [
      "Alenquer",
      "Arruda dos Vinhos",
      "Azambuja",
      "Cadaval",
      "Cascais",
      "Lisboa",
      "Loures",
      "Lourinhã",
      "Mafra",
      "Oeiras",
      "Sintra",
      "Sobral de Monte Agraço",
      "Torres Vedras",
      "Vila Franca de Xira",
      "Amadora",
      "Odivelas",
    ],
    image:
      "https://static.portadafrente.com/PF24989/lisbon-1662245_1920_1618313080601.jpg",
  },
  {
    distrito: "Portalegre",
    concelho: [
      "Alter do Chão",
      "Arronches",
      "Avis",
      "Campo Maior",
      "Castelo de Vide",
      "Crato",
      "Elvas",
      "Fronteira",
      "Gavião",
      "Marvão",
      "Monforte",
      "Nisa",
      "Ponte de Sor",
      "Portalegre",
      "Sousel",
    ],
    image: "https://kippertree.com/storage/districts/portalegre.jpg",
  },
  {
    distrito: "Porto",
    concelho: [
      "Amarante",
      "Baião",
      "Felgueiras",
      "Gondomar",
      "Lousada",
      "Maia",
      "Marco de Canaveses",
      "Matosinhos",
      "Paços de Ferreira",
      "Paredes",
      "Penafiel",
      "Porto",
      "Póvoa de Varzim",
      "Santo Tirso",
      "Trofa",
      "Valongo",
      "Vila do Conde",
      "Vila Nova de Gaia",
    ],
    image:
      "https://rare-gallery.com/uploads/posts/882182-Douro-River-Portugal-Porto-Bridges-Rivers-Boats.jpg",
  },
  {
    distrito: "Santarém",
    concelho: [
      "Abrantes",
      "Alcanena",
      "Almeirim",
      "Alpiarça",
      "Benavente",
      "Cartaxo",
      "Chamusca",
      "Constância",
      "Coruche",
      "Entroncamento",
      "Ferreira do Zêzere",
      "Golegã",
      "Mação",
      "Ourém",
      "Rio Maior",
      "Salvaterra de Magos",
      "Santarém",
      "Sardoal",
      "Tomar",
      "Torres Novas",
      "Vila Nova da Barquinha",
    ],
    image:
      "https://www.portugaldenorteasul.pt/uploads/20190717183240_asasasas.jpg",
  },
  {
    distrito: "Setúbal",
    concelho: [
      "Alcácer do Sal",
      "Alcochete",
      "Almada",
      "Barreiro",
      "Grândola",
      "Moita",
      "Montijo",
      "Palmela",
      "Santiago do Cacém",
      "Seixal",
      "Sesimbra",
      "Setúbal",
      "Sines",
    ],
    image:
      "https://img.marinas.com/v2/194cc421f80bfb964bedc2343a216dd02e712c18ef1acffdabe67389c4a607a8.jpg",
  },
  {
    distrito: "Viana do Castelo",
    concelho: [
      "Arcos de Valdevez",
      "Caminha",
      "Melgaço",
      "Monção",
      "Paredes de Coura",
      "Ponte da Barca",
      "Ponte de Lima",
      "Valença",
      "Viana do Castelo",
      "Vila Nova de Cerveira",
    ],
    image:
      "https://www.iberian-escapes.com/images/viana-do-castelo-santa-luzia.jpg",
  },
  {
    distrito: "Vila Real",
    concelho: [
      "Alijó",
      "Boticas",
      "Chaves",
      "Mesão Frio",
      "Mondim de Basto",
      "Montalegre",
      "Murça",
      "Peso da Régua",
      "Ribeira de Pena",
      "Sabrosa",
      "Santa Marta de Penaguião",
      "Valpaços",
      "Vila Pouca de Aguiar",
      "Vila Real",
    ],
    image:
      "https://g7h8x9w9.rocketcdn.me/wp-content/uploads/2022/03/que-ver-en-vila-real-portugal-scaled.jpg",
  },
  {
    distrito: "Viseu",
    concelho: [
      "Armamar",
      "Carregal do Sal",
      "Castro Daire",
      "Cinfães",
      "Lamego",
      "Mangualde",
      "Moimenta da Beira",
      "Mortágua",
      "Nelas",
      "Oliveira de Frades",
      "Penalva do Castelo",
      "Penedono",
      "Resende",
      "Santa Comba Dão",
      "São João da Pesqueira",
      "São Pedro do Sul",
      "Sátão",
      "Sernancelhe",
      "Tabuaço",
      "Tarouca",
      "Tondela",
      "Vila Nova de Paiva",
      "Viseu",
      "Vouzela",
    ],
    image:
      "https://turismodocentro.pt/wp-content/uploads/2019/12/Viseu_1920x1080.jpg",
  },
];

export default locationList;
